name: Publish NPM package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

permissions:
  contents: write

concurrency:
  group: "publish"
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.3.0

      - name: Update version in package.json
        run: |
          jq '.version = "${{ github.event.inputs.version }}"' -M package.json > tmp.json && mv tmp.json package.json

      - run: npm install
      - run: npm run format
      - run: npm run build
      # - run: npm test

      - name: Version docs
        run: |
          npm run docusaurus api:version "${{ github.event.inputs.version }}"
          npm run docusaurus docs:version "${{ github.event.inputs.version }}"
        working-directory: ./site

      - name: Commit changes
        run: |
          git config --local user.email "hello@schahriar.com"
          git config --local user.name "GitHub Action"
          git commit -am "Published v${{ github.event.inputs.version }}"
          git push

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
